sudo: true
language: cpp
matrix:
  include:
    - os: osx
      env: export HDT_CPP=clang++
    - os: osx
      env: export HDT_CPP=g++
    - os: linux
      env: export HDT_CPP=clang++
    - os: linux
      env: export HDT_CPP=g++
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: export HDT_CPP=g++-4.8
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: export HDT_CPP=g++-5
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: export HDT_CPP=g++-6
before_install:
  # Download and install SERD
  - curl -s http://download.drobilla.net/serd-0.24.0.tar.bz2 | tar -xj
  - pushd serd-* && ./waf configure && ./waf && sudo ./waf install && popd
  # Download and install Raptor
  - curl -s http://download.librdf.org/source/raptor2-2.0.15.tar.gz | tar -xz
  - pushd raptor2-* && ./configure && make -j2 && sudo make install && popd
  # Test build environment
  - $HDT_CPP --version
script:
  - cd hdt-lib
  - make -j2 CPP=$HDT_CPP
