language: cpp
env:
  global:
    - TESTS_HDT="bit375 bitutiltest listener logarr streamtest testmax"
    - TESTS_CDS="testArray testBitSequence testHuffman testLCP testNPR testSequence testSuffixTree testTextIndex timeSequence toArray2 toArray"
matrix:
  include:
    - os: osx
      env: export HDT_CPP=clang++
    - os: osx
      env: export HDT_CPP=g++
    - os: linux
      env: export HDT_CPP=clang++
    - os: linux
      env: export HDT_CPP=g++
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'zlib1g-dev']
      env: export HDT_CPP=g++-4.8
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'zlib1g-dev']
      env: export HDT_CPP=g++-5
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'zlib1g-dev']
      env: export HDT_CPP=g++-6
before_install:
  - pushd $HOME
  # Download and install Serd
  # - curl -s http://download.drobilla.net/serd-0.24.0.tar.bz2 | tar -xj
  - git clone https://github.com/drobilla/serd.git
  - pushd serd* && ./waf configure --prefix=$HOME/local && ./waf && ./waf install && popd
  # Download and install Raptor
  - curl -s http://download.librdf.org/source/raptor2-2.0.15.tar.gz | tar -xz
  - pushd raptor2-* && ./configure --prefix=$HOME/local && make -j2 && make install && popd
  # Set up build environment
  - $HDT_CPP --version
  - popd
script:
  # Build standalone binaries
  - ./autogen.sh
  - ./configure --with-serd-prefix=$HOME/local --with-raptor2-prefix=$HOME/local --prefix=$HOME CXX=$HDT_CPP
  - make -j2
  # Make and run selected tests. Most tests in HDT are failing
  - pushd libcds && TESTS=$TESTS_CDS make -e check -j2 && popd
  - pushd libhdt && TESTS=$TESTS_HDT make -e check -j2 && popd
  # Install
  - make install
  - $HOME/bin/hdtSearch -q 0 libhdt/data/literals.hdt
  # Test installation files
  - test -f $HOME/bin/hdt2rdf
  - test -f $HOME/bin/hdtInfo
  - test -f $HOME/bin/hdtSearch
  - test -f $HOME/bin/modifyHeader
  - test -f $HOME/bin/rdf2hdt
  - test -f $HOME/bin/replaceHeader
  - test -f $HOME/bin/searchHeader
  - test -f $HOME/lib/libhdt.la
  - test -f $HOME/lib/libcds.la
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then test -L $HOME/lib/libhdt.so; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then test -L $HOME/lib/libcds.so; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then test -L $HOME/lib/libhdt.dylib; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then test -L $HOME/lib/libcds.dylib; fi"
  - test -f $HOME/lib/pkgconfig/hdt.pc
  - test -f $HOME/lib/pkgconfig/cds.pc
