language: cpp
matrix:
  include:
    - os: osx
      env: export HDT_CPP=clang++
    - os: osx
      env: export HDT_CPP=g++
    - os: linux
      env: export HDT_CPP=clang++
    - os: linux
      env: export HDT_CPP=g++
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'zlib1g-dev']
      env: export HDT_CPP=g++-4.8
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'zlib1g-dev']
      env: export HDT_CPP=g++-5
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'zlib1g-dev']
      env: export HDT_CPP=g++-6
before_install:
  - pushd $HOME
  # Download and install Serd
  # - curl -s http://download.drobilla.net/serd-0.24.0.tar.bz2 | tar -xj
  - git clone https://github.com/drobilla/serd.git
  - pushd serd* && ./waf configure --prefix=$HOME/local && ./waf && ./waf install && popd
  # Download and install Raptor
  - curl -s http://download.librdf.org/source/raptor2-2.0.15.tar.gz | tar -xz
  - pushd raptor2-* && ./configure --prefix=$HOME/local && make -j2 && make install && popd
  # Set up build environment
  - $HDT_CPP --version
  - popd
script:
  # Build standalone binaries
  - ./configure --enable-libcds --with-serd-prefix=$HOME/local --with-raptor2-prefix=$HOME/local --prefix=$HOME
  - make -j $(nproc) CXX=$HDT_CPP
  # Make and run selected tests
  #- make -j2 check CXX=$HDT_CPP
  - make install
  - $HOME/bin/hdtSearch -q 0 data/literals.hdt
